import Link from "next/link";
import { HughesLogotype } from "../../components/hughes-logotype";

export default function Collateral() {
  return <main><header className="site-header shell"><Link className="wordmark" href="/"><HughesLogotype className="site-logo" /><span>STRESS BUSTERS</span></Link><nav aria-label="Primary navigation"><Link href="/">Home</Link><Link className="active" href="/collateral">Publishing Kit <span className="arrow">↗</span></Link></nav></header>
    <section className="subhero shell"><p className="eyebrow">Publishing Kit / Brand, game &amp; commerce</p><h1>Stress Busters<br /><span>ready to play.</span></h1><p className="lede">A bright little game with a real print spec, a clear retail story, and a web home ready to share.</p></section>
    <section className="section shell"><div className="section-heading"><p className="eyebrow">01 / Hi-fi mockups</p><p className="muted">Direction for a compact, tactile edition.</p></div><div className="mockup-stage"><div className="mockup-card mockup-stress"><HughesLogotype className="card-logo" /><h2>STRESS<br />BUSTERS!</h2><img className="card-illustration" src="/stress-busters-illustration.png" alt="Line drawing of a human face beside a skull" /><div className="mockup-footer">ARE YOU AWAKE NOW?</div></div><div className="mockup-card mockup-buster"><div className="mockup-label">STRESS BUSTERS</div><img className="card-two-illustration" src="/i-scream-illustration.jpeg" alt="Painted melting ice cream skull by the sea" /><h2>I<br />SCREAM!</h2><div className="mockup-footer">A MATCHING GAME FOR UNMATCHED DAYS</div></div><div className="mockup-card mockup-blank"><div className="mockup-label">STRESS BUSTERS</div><div className="blank-lines"><span></span><span></span><span></span></div><p>WRITE YOUR<br />OWN BUSTER</p><div className="mockup-footer">70 × 120 MM / BLANK STOCK</div></div></div></section>
    <section className="section shell split-section specs"><div><p className="eyebrow">02 / Print spec</p><h2>Simple materials.<br />Strong point of view.</h2></div><div className="spec-list"><div><span>Format</span><strong>70 × 120 mm<br />Card format</strong></div><div><span>Stock</span><strong>350 gsm uncoated<br />Natural white</strong></div><div><span>Finish</span><strong>Black ink / blind deboss<br />Rounded corners</strong></div><div><span>Set</span><strong>10 cards + 1 joker<br />Small tuck box</strong></div></div></section>
    <section className="section shell wireframe-section"><div className="section-heading"><p className="eyebrow">03 / Packaging wireframe</p><p className="muted">One box. No visual noise.</p></div><div className="box-wireframe"><div className="box-top">HUGHESSS [BRAND]<span>SB—01</span></div><div className="box-center"><span>STRESS</span><strong>BUSTERS</strong><small>A GAME FOR<br />THE MOMENT</small></div><div className="box-side">10 / 5 / 1</div></div></section>
    <section className="section shell launch-financials"><div className="section-heading"><p className="eyebrow">04 / Launch financials</p><p className="muted">Small run assumptions - update before ordering.</p></div><div className="finance-grid"><div><span>Prototype print</span><strong>$167.16</strong><p>Estimate for five 25-card decks, 70 × 120 mm, CMYK laminated stock and tuck boxes.</p></div><div><span>Per-deck print</span><strong>$33.43</strong><p>Prototype cost before freight and handling.</p></div><div><span>Web ops</span><strong>$0–20/mo</strong><p>Vercel Hobby at launch, or Pro at $20/month once the shop needs a business plan.</p></div><div><span>Design to date</span><strong>$1,200*</strong><p>Working estimate: 12 hours of identity, deck art direction, web and launch setup at $100/hour.</p></div></div><div className="retail-note"><h2>A simple retail story.</h2><p>Example only: at a $55 retail price, allocate $5 per deck to Friends of the Koala, keep a separate shipping allowance, and review actual print and fulfilment costs before launch.</p><a className="text-link" href="https://friendsofthekoala.org/" target="_blank" rel="noreferrer">Friends of the Koala ↗</a></div></section>
    <footer className="footer shell"><p><HughesLogotype className="footer-logo" /><span>STRESS BUSTERS</span></p><Link href="/">Back to the game ↗</Link><p className="muted">Publishing Kit / Edition 01</p></footer></main>;
}
