import Link from "next/link";

export default function Collateral() {
  return <main><header className="site-header shell"><Link className="wordmark" href="/">HUGHES / STRESS BUSTERS</Link><nav aria-label="Primary navigation"><Link href="/">Home</Link><Link className="active" href="/collateral">Collateral <span className="arrow">↗</span></Link></nav></header>
    <section className="subhero shell"><p className="eyebrow">Collateral / Print direction</p><h1>Stress Busters<br /><span>in print.</span></h1><p className="lede">A compact card set with enough room for a very specific problem, and a very good way out.</p></section>
    <section className="section shell"><div className="section-heading"><p className="eyebrow">01 / Hi-fi mockups</p><p className="muted">Direction for a compact, tactile edition.</p></div><div className="mockup-stage"><div className="mockup-card mockup-stress"><div className="mockup-label">STRESS BUSTERS</div><div className="mockup-number">01</div><h2>THE<br />PITCH</h2><div className="mockup-footer">HUGHES [BRAND] / PLAY NICE</div></div><div className="mockup-card mockup-buster"><div className="mockup-label">STRESS BUSTERS</div><div className="burst">✳</div><h2>TAKE<br />FIVE</h2><div className="mockup-footer">A MATCHING GAME FOR UNMATCHED DAYS</div></div><div className="mockup-card mockup-blank"><div className="mockup-label">STRESS BUSTERS</div><div className="blank-lines"><span></span><span></span><span></span></div><p>WRITE YOUR<br />OWN BUSTER</p><div className="mockup-footer">70 × 120 MM / BLANK STOCK</div></div></div></section>
    <section className="section shell split-section specs"><div><p className="eyebrow">02 / Print spec</p><h2>Simple materials.<br />Strong point of view.</h2></div><div className="spec-list"><div><span>Format</span><strong>70 × 120 mm<br />Card format</strong></div><div><span>Stock</span><strong>350 gsm uncoated<br />Natural white</strong></div><div><span>Finish</span><strong>Black ink / blind deboss<br />Rounded corners</strong></div><div><span>Set</span><strong>10 cards + 1 joker<br />Small tuck box</strong></div></div></section>
    <section className="section shell wireframe-section"><div className="section-heading"><p className="eyebrow">03 / Packaging wireframe</p><p className="muted">One box. No visual noise.</p></div><div className="box-wireframe"><div className="box-top">HUGHES [BRAND]<span>SB—01</span></div><div className="box-center"><span>STRESS</span><strong>BUSTERS</strong><small>A GAME FOR<br />THE MOMENT</small></div><div className="box-side">10 / 5 / 1</div></div></section>
    <footer className="footer shell"><p>HUGHES [BRAND] / STRESS BUSTERS</p><Link href="/">Back to the game ↗</Link><p className="muted">Collateral direction / Edition 01</p></footer></main>;
}
